<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Primary_FirstName</name>
   <tag></tag>
   <elementGuidId>85119234-15d9-4dbd-aff5-0d74e5ce8bbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//form[1]/div[1]/div[2]/mat-form-field/div/div[1]/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-input-30</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//form[1]/div[1]/div[2]/mat-form-field/div/div[1]/div/input</value>
   </webElementProperties>
</WebElementEntity>
