<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Primary_LastName</name>
   <tag></tag>
   <elementGuidId>491ea929-31f0-4106-b293-1666a93a7bd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//form[1]/div[1]/div[3]/mat-form-field/div/div[1]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//form[1]/div[1]/div[3]/mat-form-field/div/div[1]/div/input</value>
   </webElementProperties>
</WebElementEntity>
