<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Joint_Holder_PhoneNo</name>
   <tag></tag>
   <elementGuidId>95632917-fc96-430c-bbd8-63e800631ce0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//form/div/div/div[3]/div[1]/mat-form-field/div/div[1]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//form/div/div/div[3]/div[1]/mat-form-field/div/div[1]/div/input</value>
   </webElementProperties>
</WebElementEntity>
