<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Joint_Holder_LastName</name>
   <tag></tag>
   <elementGuidId>564ac1b1-a5fe-4360-91e2-dd3c08cb46bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//form/div/div/div[2]/div[3]/mat-form-field/div/div[1]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//form/div/div/div[2]/div[3]/mat-form-field/div/div[1]/div/input</value>
   </webElementProperties>
</WebElementEntity>
