<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_Selling</name>
   <tag></tag>
   <elementGuidId>a288d9f7-7186-4994-84a0-de23169451cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class='ng-star-inserted']//ul//li[2]//span[contains(text(),'Selling')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class='ng-star-inserted']//ul//li[2]//span[contains(text(),'Selling')]</value>
   </webElementProperties>
</WebElementEntity>
