<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Role_Value</name>
   <tag></tag>
   <elementGuidId>8756e5a1-adce-43d7-a48f-a27e7b81e823</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;inviteMemberForm&quot;]//ul//p-dropdownitem[2]/li/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;inviteMemberForm&quot;]//ul//p-dropdownitem[2]/li/span</value>
   </webElementProperties>
</WebElementEntity>
