<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Role_DD</name>
   <tag></tag>
   <elementGuidId>6573ae1d-9662-4c87-ba45-301f408460d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;inviteMemberModal&quot;]//div[@class='ui-dropdown-label-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;inviteMemberModal&quot;]//div[@class='ui-dropdown-label-container']</value>
   </webElementProperties>
</WebElementEntity>
