<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>get_created_First_Property_Details</name>
   <tag></tag>
   <elementGuidId>8eb0c10d-057a-4f50-b849-43d035db143f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//app-carousel//ul/li[1]//div[@class='buy-progress-of-house']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//app-carousel//ul/li[1]//div[@class='buy-progress-of-house']</value>
   </webElementProperties>
</WebElementEntity>
