<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>get_second_Quote_on_tab</name>
   <tag></tag>
   <elementGuidId>b8535576-8b50-43a2-8d22-6fa6a57f57cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//section[2]//div[@class='property-title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//section[2]//div[@class='property-title']</value>
   </webElementProperties>
</WebElementEntity>
