<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>get_first_Quote_on_tab</name>
   <tag></tag>
   <elementGuidId>46a16b5f-0283-43ce-a80a-8d99781db50c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//section[1]//div[@class='property-title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//section[1]//div[@class='property-title']</value>
   </webElementProperties>
</WebElementEntity>
