<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>get_created_Second_Property_Details</name>
   <tag></tag>
   <elementGuidId>9a0a4452-5b26-4ff7-835d-e6fa146ea22c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//app-carousel//ul/li[2]//div[@class='buy-progress-of-house']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//app-carousel//ul/li[2]//div[@class='buy-progress-of-house']</value>
   </webElementProperties>
</WebElementEntity>
