<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>parent_Step_value</name>
   <tag></tag>
   <elementGuidId>eff6540b-e4ca-4457-a7fc-0b6fd5e359d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li//span[contains(text(),'Mortgage')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li//span[contains(text(),'Mortgage')]</value>
   </webElementProperties>
</WebElementEntity>
