<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Send</name>
   <tag></tag>
   <elementGuidId>d5945530-8744-4755-bad1-5aff4111f32a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[starts-with(@id,'send-button-padding')]//button[contains(text(),'Send')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath1</name>
      <type>Main</type>
      <value>//div[@id='send-button-padding']//button[contains(text(),'Send')]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[starts-with(@id,'send-button-padding')]//button[contains(text(),'Send')]</value>
   </webElementProperties>
</WebElementEntity>
