<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Price_Of_Property</name>
   <tag></tag>
   <elementGuidId>cc2de4d8-c753-4883-b6eb-96813a15382e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input#mat-input-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@formcontrolname='sellingPrice']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@formcontrolname='sellingPrice']</value>
   </webElementProperties>
</WebElementEntity>
