<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_Channels</name>
   <tag></tag>
   <elementGuidId>9611de7d-fc8f-4e18-9d12-603cb31ab08f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='headingOne']//*[contains(text(),'Channels')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='headingOne']//*[contains(text(),'Channels')]</value>
   </webElementProperties>
</WebElementEntity>
