<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>get_PendingMember</name>
   <tag></tag>
   <elementGuidId>74ef4d20-2dd3-42bd-8afc-de4382180eaa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;collapseThree&quot;]//div[@class='channel-wrapper']//p[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;collapseThree&quot;]//div[@class='channel-wrapper']//p[1]</value>
   </webElementProperties>
</WebElementEntity>
