<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>column_VAT</name>
   <tag></tag>
   <elementGuidId>88bcffaf-b508-4523-8d98-a26de630466a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tbody[1]/tr[1]/th[contains(text(),'VAT(£)')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tbody[1]/tr[1]/th[contains(text(),'VAT(£)')]</value>
   </webElementProperties>
</WebElementEntity>
