<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>column_GROSS</name>
   <tag></tag>
   <elementGuidId>efacdd85-b6e1-4926-9e60-c9125513ee9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tbody[1]/tr[1]/th[contains(text(),'GROSS(£)')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tbody[1]/tr[1]/th[contains(text(),'GROSS(£)')]</value>
   </webElementProperties>
</WebElementEntity>
