<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>View_Details</name>
   <tag></tag>
   <elementGuidId>4b21354d-6972-4de2-9062-fbed198aae10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//app-listing/div[1]/div[1]/div[2]/p[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//app-listing/div[1]/div[1]/div[2]/p[3]</value>
   </webElementProperties>
</WebElementEntity>
